// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCPFwLe9zlsosv0By86FX3HqwUGO6pRCw',
    appId: '1:108620866774:web:ccc186ae4f2f4524251577',
    messagingSenderId: '108620866774',
    projectId: 'post-it-91a3d',
    authDomain: 'post-it-91a3d.firebaseapp.com',
    storageBucket: 'post-it-91a3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_gWYkg4MSkgsgCUJdsKlcFM8kOCIIZM',
    appId: '1:108620866774:android:0cebc38d0773ba4e251577',
    messagingSenderId: '108620866774',
    projectId: 'post-it-91a3d',
    storageBucket: 'post-it-91a3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg9oKeF-1c5W5rbx4Uhkcx2Qq56SC_Km4',
    appId: '1:108620866774:ios:34041d4602871930251577',
    messagingSenderId: '108620866774',
    projectId: 'post-it-91a3d',
    storageBucket: 'post-it-91a3d.appspot.com',
    iosClientId:
        '108620866774-8bff29a32s4h37duku59pih53inkn9hj.apps.googleusercontent.com',
    iosBundleId: 'com.mateuszgadomski.postIt',
  );
}
